const DishesList = [
  [
    {
      source: "/vertical/日本和牛/日本A5和牛菲力.jpg",
      name: "日本A5和牛菲力",
      name_hant: "日本A5和牛菲力",
      enname: "A5 WAGYU FILET MIGNON",
      des: [
        "仅选用顶级A5和牛，选以最精致的部位，",
        "著以些许调味，雪花般的纹理和独有的香气，",
        "在嘴中肆意的冲击着您的味蕾，",
        "犹如“无声细下飞碎雪，放著未觉全盘空”。",
      ],
      des_hant: [
        "僅選用頂級A5和牛，選以最精緻的部位，",
        "著以些許調味，雪花般的紋理和獨有的香氣，",
        "在嘴中肆意的衝擊着您的味蕾，",
        "猶如“無聲細下飛碎雪，放著未覺全盤空”。",
      ],
      endes: `  Select only top A5 Wagyu cattle, select the most delicate parts,.  
      With a touch of seasoning, snowflake texture and unique aroma,  
      Pounding your taste buds in your mouth,  
      It is like" the snow falls silently, but it is not completely empty.`,
    },
    {
      source: "/vertical/日本和牛/日本A5和牛肋眼心.jpg",
      name: "日本A5和牛肋眼心",
      name_hant: "日本A5和牛肋眼心",
      enname: "A5 WAGYU RIBEYE ROLL",
      des: [
        "仅选用顶级A5和牛，选以最精致的部位，",
        "著以些许调味，雪花般的纹理和独有的香气，",
        "在嘴中肆意的冲击着您的味蕾，",
        "犹如“无声细下飞碎雪，放著未觉全盘空”。",
      ],
      des_hant: [
        "僅選用頂級A5和牛，選以最精緻的部位，",
        "著以些許調味，雪花般的紋理和獨有的香氣，",
        "在嘴中肆意的衝擊着您的味蕾，",
        "猶如“無聲細下飛碎雪，放著未覺全盤空”。",
      ],
      endes: `  Select only top A5 Wagyu cattle, select the most delicate parts,.  
      With a touch of seasoning, snowflake texture and unique aroma,  
      Pounding your taste buds in your mouth,  
      It is like" the snow falls silently, but it is not completely empty.`,
    },
    {
      source: "/vertical/日本和牛/日本A5和牛紐約客壽喜燒.jpg",
      name: "日本A5和牛纽约客寿喜烧 ",
      name_hant: "日本A5和牛紐約客壽喜燒",
      enname: "A5 WAGYU SUKIYAKI",
      des: [
        "仅选用顶级A5和牛，选以最精致的部位，",
        "著以些许调味，雪花般的纹理和独有的香气，",
        "在嘴中肆意的冲击着您的味蕾，",
        "犹如“无声细下飞碎雪，放著未觉全盘空”。",
      ],
      des_hant: [
        "僅選用頂級A5和牛，選以最精緻的部位，",
        "著以些許調味，雪花般的紋理和獨有的香氣，",
        "在嘴中肆意的衝擊着您的味蕾，",
        "猶如“無聲細下飛碎雪，放著未覺全盤空”。",
      ],
      endes: `  Select only top A5 Wagyu cattle, select the most delicate parts,.  
      With a touch of seasoning, snowflake texture and unique aroma,  
      Pounding your taste buds in your mouth,  
      It is like" the snow falls silently, but it is not completely empty.`,
    },
  ],
  [
    {
      source: "/vertical/澳洲和牛/澳洲和牛DNA牛舌.jpg",
      name: "澳洲和牛DNA牛舌",
      name_hant: "澳洲和牛DNA牛舌",
      enname: "AUS WAGYU DNA TONGGUE",
      des: [
        "有别于日本和牛，细选和牛特色部位，",
        "配以精心烹灼，初尝的是甜香牛油，口齿皆香",
        "轻咬一口，口感滑嫩多汁，",
        "让您感受到极致和牛的鲜香美味",
        "最美味的烧肉，在此间绽放于您的口中",
      ],
      des_hant: [
        "有別於日本和牛，細選和牛特色部位，",
        "配以精心烹灼，初嘗的是甜香牛油，口齒皆香",
        "輕咬一口，口感滑嫩多汁，",
        "讓您感受到極致和牛的鮮香美味",
        "最美味的燒肉，在此間綻放於您的口中",
      ],
      endes: `   Different from Japanese Wagyu cattle, selected Wagyu characteristic parts, 
      It is well cooked, and the first taste is sweet butter, and the taste is sweet to the mouth. 
      A little bite, it's smooth and juicy,
      Let you feel the ultimate wagyu beef delicious,
      The most delicious roast meat blooms in your mouth here.`,
    },
    {
      source: "/vertical/澳洲和牛/澳洲和牛辮子肉.jpg",
      name: "澳洲和牛辮子肉",
      name_hant: "澳洲和牛辮子肉",
      enname: "JAPANESE YAM",
      des: [
        "有别于日本和牛，细选和牛特色部位，",
        "配以精心烹灼，初尝的是甜香牛油，口齿皆香",
        "轻咬一口，口感滑嫩多汁，",
        "让您感受到极致和牛的鲜香美味",
        "最美味的烧肉，在此间绽放于您的口中",
      ],
      des_hant: [
        "有別於日本和牛，細選和牛特色部位，",
        "配以精心烹灼，初嘗的是甜香牛油，口齒皆香",
        "輕咬一口，口感滑嫩多汁，",
        "讓您感受到極致和牛的鮮香美味",
        "最美味的燒肉，在此間綻放於您的口中",
      ],
      endes: `   Different from Japanese Wagyu cattle, selected Wagyu characteristic parts, 
      It is well cooked, and the first taste is sweet butter, and the taste is sweet to the mouth. 
      A little bite, it's smooth and juicy,
      Let you feel the ultimate wagyu beef delicious,
      The most delicious roast meat blooms in your mouth here.`,
    },
    {
      source: "/vertical/澳洲和牛/澳洲和牛厚切牛舌.jpg",
      name: "澳洲和牛厚切牛舌",
      name_hant: "澳洲和牛厚切牛舌",
      enname: "AUS WAGYU THICK CUT TONGUE",
      des: [
        "有别于日本和牛，细选和牛特色部位，",
        "配以精心烹灼，初尝的是甜香牛油，口齿皆香",
        "轻咬一口，口感滑嫩多汁，",
        "让您感受到极致和牛的鲜香美味",
        "最美味的烧肉，在此间绽放于您的口中",
      ],
      des_hant: [
        "有別於日本和牛，細選和牛特色部位，",
        "配以精心烹灼，初嘗的是甜香牛油，口齒皆香",
        "輕咬一口，口感滑嫩多汁，",
        "讓您感受到極致和牛的鮮香美味",
        "最美味的燒肉，在此間綻放於您的口中",
      ],
      endes: `   Different from Japanese Wagyu cattle, selected Wagyu characteristic parts, 
      It is well cooked, and the first taste is sweet butter, and the taste is sweet to the mouth. 
      A little bite, it's smooth and juicy,
      Let you feel the ultimate wagyu beef delicious,
      The most delicious roast meat blooms in your mouth here.`,
    },
    {
      source: "/vertical/澳洲和牛/澳洲和牛內橫隔膜.jpg",
      name: "澳洲和牛內橫隔膜",
      name_hant: "澳洲和牛內橫隔膜",
      enname: "AUS WAGYU MS8 INSIDE SKIRT",
      des: [
        "有别于日本和牛，细选和牛特色部位，",
        "配以精心烹灼，初尝的是甜香牛油，口齿皆香",
        "轻咬一口，口感滑嫩多汁，",
        "让您感受到极致和牛的鲜香美味",
        "最美味的烧肉，在此间绽放于您的口中",
      ],
      des_hant: [
        "有別於日本和牛，細選和牛特色部位，",
        "配以精心烹灼，初嘗的是甜香牛油，口齒皆香",
        "輕咬一口，口感滑嫩多汁，",
        "讓您感受到極致和牛的鮮香美味",
        "最美味的燒肉，在此間綻放於您的口中",
      ],
      endes: `   Different from Japanese Wagyu cattle, selected Wagyu characteristic parts, 
      It is well cooked, and the first taste is sweet butter, and the taste is sweet to the mouth. 
      A little bite, it's smooth and juicy,
      Let you feel the ultimate wagyu beef delicious,
      The most delicious roast meat blooms in your mouth here.`,
    },
    {
      source: "/vertical/澳洲和牛/澳洲和牛厚切牛舌.jpg",
      name: "澳洲和牛舌",
      name_hant: "澳洲和牛舌",
      enname: "AUS WAGYU THIN CUT TONGUE",
      des: [
        "有别于日本和牛，细选和牛特色部位，",
        "配以精心烹灼，初尝的是甜香牛油，口齿皆香",
        "轻咬一口，口感滑嫩多汁，",
        "让您感受到极致和牛的鲜香美味",
        "最美味的烧肉，在此间绽放于您的口中",
      ],

      des_hant: [
        "有別於日本和牛，細選和牛特色部位，",
        "配以精心烹灼，初嘗的是甜香牛油，口齒皆香",
        "輕咬一口，口感滑嫩多汁，",
        "讓您感受到極致和牛的鮮香美味",
        "最美味的燒肉，在此間綻放於您的口中",
      ],
      endes: `   Different from Japanese Wagyu cattle, selected Wagyu characteristic parts, 
      It is well cooked, and the first taste is sweet butter, and the taste is sweet to the mouth. 
      A little bite, it's smooth and juicy,
      Let you feel the ultimate wagyu beef delicious,
      The most delicious roast meat blooms in your mouth here.`,
    },
    {
      source: "/vertical/澳洲和牛/澳洲和牛舌下肉.jpg",
      name: "澳洲和牛舌下肉",
      name_hant: "澳洲和牛舌下肉",
      enname: "AUS WAGYU LOWER PORTION OF TONGUE",
      des: [
        "有别于日本和牛，细选和牛特色部位，",
        "配以精心烹灼，初尝的是甜香牛油，口齿皆香",
        "轻咬一口，口感滑嫩多汁，",
        "让您感受到极致和牛的鲜香美味",
        "最美味的烧肉，在此间绽放于您的口中",
      ],
      des_hant: [
        "有別於日本和牛，細選和牛特色部位，",
        "配以精心烹灼，初嘗的是甜香牛油，口齒皆香",
        "輕咬一口，口感滑嫩多汁，",
        "讓您感受到極致和牛的鮮香美味",
        "最美味的燒肉，在此間綻放於您的口中",
      ],
      endes: `   Different from Japanese Wagyu cattle, selected Wagyu characteristic parts, 
      It is well cooked, and the first taste is sweet butter, and the taste is sweet to the mouth. 
      A little bite, it's smooth and juicy,
      Let you feel the ultimate wagyu beef delicious,
      The most delicious roast meat blooms in your mouth here.`,
    },
    {
      source: "/vertical/澳洲和牛/澳洲和牛和牛菲力.jpg",
      name: "澳洲和牛菲力",
      name_hant: "澳洲和牛菲力",
      enname: "AUS WAGYU FILI",
      des: [
        "挑选日本A5和牛牛嵴上最嫩的肉——菲力",
        "其脂肪含量低，肉质软嫩",
        "口感如奶油般嫩滑",
        "味道咸香鲜嫩非常适合老人和小孩食用。",
      ],
      des_hant: [
        "挑選日本A5和牛牛脊上最嫩的肉——菲力",
        "其脂肪含量低，肉質軟嫩",
        "口感如奶油般嫩滑",
        "味道鹹香鮮嫩非常適合老人和小孩食用。",
      ],
      endes: `   Choose the tenderest meat on Japanese A5 Wagyu sirloin - filet, 
      which has low fat content, soft and tender meat,
       creamy and tender taste, salty, fragrant and tender.
        It is very suitable for the elderly and children.`,
    },
    {
      source: "/vertical/澳洲和牛/澳洲和牛和牛壺漬.jpg",
      name: "澳洲和牛壺漬",
      name_hant: "澳洲和牛壺漬",
      enname: "AUS WAGYU POT STAIN",
      des: [
        "严选安美国达拉斯牛肉",
        "细嫩又紧实的肌肉层叠交融",
        "醇厚多汁且甘甜",
        "配以着重酱烧调味工艺",
        "让简单的石紋澳洲和牛壺漬却藏着人间最好的美味",
      ],
      des_hant: [
        "嚴選安美國達拉斯牛肉",
        "細嫩又緊實的肌肉層疊交融",
        "醇厚多汁且甘甜",
        "配以着重醬燒調味工藝",
        "讓簡單的石紋澳洲和牛壺漬卻藏着人間最好的美味",
      ],
      endes: `      Thick, juicy and sweet ,  `,
    },
    {
      source: "/vertical/澳洲和牛/澳洲和牛和牛牛小排.jpg",
      name: "澳洲和牛牛小排",
      name_hant: "澳洲和牛牛小排",
      enname: "AUS WAGYU BEEF SHORT STEAK",
      des: [
        "精选优质牛的前胸牛小排牛，",
        "密集的雪花脂肪纹路以及较薄的厚度，。",
        "炭烧中必不可少的肉品，",
        "吃进嘴里时感觉随着每次咀嚼脂肪的蓬勃而出，",
        "让人欲罢不能。",
      ],
      des_hant: [
        "精選優質牛的前胸牛小排牛，",
        "密集的雪花脂肪紋路以及較薄的厚度，。",
        "炭燒中必不可少的肉品，",
        "吃進嘴裏時感覺隨著每次咀嚼脂肪的蓬勃而出，",
        "讓人欲罷不能。",
      ],
      endes: `   Selected high-quality beef brisket steak, dense snowflake fat texture and thin thickness,
       an indispensable meat in charcoal roasting, when you eat it into your mouth,
        you feel that the fat comes out vigorously with each chewing, allowing People can't stop.`,
    },
  ],
  [
    {
      source: "/vertical/美国牛肉/美國達拉斯.jpg",
      name: "美国达拉斯 ",
      name_hant: "美國達拉斯",
      enname: "US PRIME DALLAS CUBE",
      des: [
        "严选安美国达拉斯牛肉",
        "细嫩又紧实的肌肉层叠交融",
        "醇厚多汁且甘甜",
        "配以着重酱烧调味工艺",
        "让简单的石紋牛小排却藏着人间最好的美味",
      ],
      des_hant: [
        "嚴選安美國達拉斯牛肉",
        "細嫩又緊實的肌肉層疊交融",
        "醇厚多汁且甘甜",
        "配以着重醬燒調味工藝",
        "讓簡單的石紋牛小排卻藏着人間最好的美味",
      ],
      endes: ` Yan Xuan An American Dallas Beef ,  `,
    },
    {
      source: "/vertical/美国牛肉/美國頂級肋眼牛排.jpg",
      name: "美国顶级肋眼牛排",
      name_hant: "美國頂級肋眼牛排",
      enname: "US PRIME RIBEYE STEAK",
      des: [
        "严选安美国达拉斯牛肉",
        "细嫩又紧实的肌肉层叠交融",
        "醇厚多汁且甘甜",
        "配以着重酱烧调味工艺",
        "让简单的石紋牛小排却藏着人间最好的美味",
      ],
      des_hant: [
        "嚴選安美國達拉斯牛肉",
        "細嫩又緊實的肌肉層疊交融",
        "醇厚多汁且甘甜",
        "配以着重醬燒調味工藝",
        "讓簡單的石紋牛小排卻藏着人間最好的美味",
      ],
      endes: `      Layers of tender, firm muscle,  `,
    },
    {
      source: "/vertical/美国牛肉/美國牛肋條.jpg",
      name: "美国牛肋条",
      name_hant: "美國牛肋條",
      enname: "US CHOICE RIB STRIP",
      des: [
        "严选安美国达拉斯牛肉",
        "细嫩又紧实的肌肉层叠交融",
        "醇厚多汁且甘甜",
        "配以着重酱烧调味工艺",
        "让简单的石紋牛小排却藏着人间最好的美味",
      ],
      des_hant: [
        "嚴選安美國達拉斯牛肉",
        "細嫩又緊實的肌肉層疊交融",
        "醇厚多汁且甘甜",
        "配以着重醬燒調味工藝",
        "讓簡單的石紋牛小排卻藏着人間最好的美味",
      ],
      endes: `      Thick, juicy and sweet ,  `,
    },
    {
      source: "/vertical/美国牛肉/美國去骨牛小排.jpg",
      name: "美国去骨牛小排 ",
      name_hant: "美國去骨牛小排",
      enname: "US PRIME BONELESS SHORT RIB",
      des: [
        "严选安美国达拉斯牛肉",
        "细嫩又紧实的肌肉层叠交融",
        "醇厚多汁且甘甜",
        "配以着重酱烧调味工艺",
        "让简单的石紋牛小排却藏着人间最好的美味",
      ],
      des_hant: [
        "嚴選安美國達拉斯牛肉",
        "細嫩又緊實的肌肉層疊交融",
        "醇厚多汁且甘甜",
        "配以着重醬燒調味工藝",
        "讓簡單的石紋牛小排卻藏着人間最好的美味",
      ],
      endes: `      Seasoning with heavy sauce ,  `,
    },
    {
      source: "/vertical/美国牛肉/御作海膽炙牛肉(美國).jpg",
      name: "御作海胆炙牛肉 ",
      name_hant: "御作海膽炙牛肉",
      enname: "JABURI US BEFF WITH UNI NIGIRI",
      des: [
        "严选安美国达拉斯牛肉",
        "细嫩又紧实的肌肉层叠交融",
        "醇厚多汁且甘甜",
        "配以着重酱烧调味工艺",
        "让简单的石紋牛小排却藏着人间最好的美味",
      ],
      des_hant: [
        "嚴選安美國達拉斯牛肉",
        "細嫩又緊實的肌肉層疊交融",
        "醇厚多汁且甘甜",
        "配以着重醬燒調味工藝",
        "讓簡單的石紋牛小排卻藏着人間最好的美味",
      ],
      endes: `      Let a simple stone rib of beef hide the finest taste in the world,`,
    },
  ],

  [
    {
      source: "/vertical/猪肉/伊比利豬肩排.jpg",
      name: "伊比利豬肩排",
      name_hant: "伊比利豬肩排",
      enname: "JIBERICO PORK SHOULDER BLADE",
      des: [
        "特选西班牙伊比利猪肩排",
        "肉质纯净且带有淡淡核果香味",
        "单纯加入盐之花",
        "炭火烧制，凸显原始风味",
        "每口的肩排都口感香嫩，脂香恰到好处，",
        "沉浸式享受此间美味",
      ],
      des_hant: [
        "特選西班牙伊比利豬肩排",
        "肉質純淨且帶有淡淡核果香味",
        "單純加入鹽之花",
        "炭火燒製，凸顯原始風味",
        "每口的肩排都口感香嫩，脂香恰到好處，",
        "沉浸式享受此間美味",
      ],
      endes: ` Iberico Pork Shoulder Steak of Choice ,  
      Pure meat with a light stone fruit flavour ,  
      Just add the salt flower,  
      Charcoal fire to highlight the original flavor,
      Every bite of the shoulder steak is tender and just right,  
      Immerse yourself in this delicious food , `,
    },
    {
      source: "/vertical/日本和牛/日本A5和牛菲力.jpg",
      name: "日本A5和牛菲力",
      name_hant: "日本A5和牛菲力",
      enname: "IBERICO PORK SHOULDER BLADE",
      des: [
        "特选西班牙伊比利猪肩排",
        "肉质纯净且带有淡淡核果香味",
        "单纯加入盐之花",
        "炭火烧制，凸显原始风味",
        "每口的肩排都口感香嫩，脂香恰到好处，",
        "沉浸式享受此间美味",
      ],
      des_hant: [
        "特選西班牙伊比利豬肩排",
        "肉質純淨且帶有淡淡核果香味",
        "單純加入鹽之花",
        "炭火燒製，凸顯原始風味",
        "每口的肩排都口感香嫩，脂香恰到好處，",
        "沉浸式享受此間美味",
      ],
      endes: ` Iberico Pork Shoulder Steak of Choice ,  
      Pure meat with a light stone fruit flavour ,  
      Just add the salt flower,  
      Charcoal fire to highlight the original flavor,
      Every bite of the shoulder steak is tender and just right,  
      Immerse yourself in this delicious food , `,
    },
    {
      source: "/vertical/日本和牛/日本A5和牛肋眼心.jpg",
      name: "日本A5和牛肋眼心",
      name_hant: "日本A5和牛肋眼心",
      enname: "IBERICO PORK SHOULDER BLADE",
      des: [
        "特选西班牙伊比利猪肩排",
        "肉质纯净且带有淡淡核果香味",
        "单纯加入盐之花",
        "炭火烧制，凸显原始风味",
        "每口的肩排都口感香嫩，脂香恰到好处，",
        "沉浸式享受此间美味",
      ],
      des_hant: [
        "特選西班牙伊比利豬肩排",
        "肉質純淨且帶有淡淡核果香味",
        "單純加入鹽之花",
        "炭火燒製，凸顯原始風味",
        "每口的肩排都口感香嫩，脂香恰到好處，",
        "沉浸式享受此間美味",
      ],
      endes: ` Iberico Pork Shoulder Steak of Choice ,  
      Pure meat with a light stone fruit flavour ,  
      Just add the salt flower,  
      Charcoal fire to highlight the original flavor,
      Every bite of the shoulder steak is tender and just right,  
      Immerse yourself in this delicious food , `,
    },
  ],
  [
    {
      source: "/vertical/鸡肉/雞軟骨.jpg",
      name: "鸡软骨 ",
      name_hant: "雞軟骨",
      enname: "CHICKEN CARTILAGE SOFT BONE",
      des: [
        "精选每只鸡的鸡胸软骨和鸡腿",
        "配以独家研制酱料",
        "配以炭火烤烧，口感绝美",
        "每块软骨和无骨鸡腿肉搭配一口清酒",
        "美酒佳肴具兼得",
      ],
      des_hant: [
        "精選每隻雞的雞胸軟骨和雞腿",
        "配以獨家研製醬料",
        "配以炭火烤燒，口感絕美",
        "每塊軟骨和無骨雞腿肉搭配一口清酒",
        "美酒佳餚具兼得",
      ],
      endes: `    Select the breast cartilage and legs of each chicken ,  
      Served with an exclusive sauce,  
      It's beautiful when it's grilled over a charcoal fire, 
      Each piece of cartilage and boneless chicken leg with a sip of sake, 
      Wine, food and food , `,
    },
    {
      source: "/vertical/鸡肉/去骨土雞腿肉.jpg",
      name: "去骨土鸡腿肉",
      name_hant: "去骨土雞腿肉",
      enname: "BONELESS CHICKEN THIGH",
      des: [
        "精选每只鸡的鸡胸软骨和鸡腿",
        "配以独家研制酱料",
        "配以炭火烤烧，口感绝美",
        "每块软骨和无骨鸡腿肉搭配一口清酒",
        "美酒佳肴具兼得",
      ],
      des_hant: [
        "精選每隻雞的雞胸軟骨和雞腿",
        "配以獨家研製醬料",
        "配以炭火烤燒，口感絕美",
        "每塊軟骨和無骨雞腿肉搭配一口清酒",
        "美酒佳餚具兼得",
      ],
      endes: `    Select the breast cartilage and legs of each chicken ,  
      Served with an exclusive sauce,  
      It's beautiful when it's grilled over a charcoal fire, 
      Each piece of cartilage and boneless chicken leg with a sip of sake, 
      Wine, food and food , `,
    },
    {
      source: "/vertical/鸡肉/焱烤手羽先.jpg",
      name: "焱烤手羽先",
      name_hant: "焱烤手羽先",
      enname: "FRIST A HAND IS ROASTED",
      des: ["鸡肉与蔬菜、水果的交融，", "口感脆嫩微甜，健康又美味", "", ""],
      des_hant: [
        "雞肉與蔬菜、水果的交融，",
        "口感脆嫩微甜，健康又美味",
        "",
        "",
      ],
      endes: `   The combination of chicken with vegetables and fruits 
      makes it crisp and sweet, healthy and delicious. `,
    },
  ],
  [
    {
      source: "/vertical/羊肉/羊肉.jpg",
      name: "羊肉",
      name_hant: "羊肉",
      enname: "FRENCHED LAMB CHOP",
      des: [
        "细选优质羊排骨中肋骨瘦小的部分羊小排，肉层厚实，有软骨",
        "肥瘦结合，质地松软，肉质鲜美柔嫩",
        "古医有云“羊肉能暖中补虚,补中益气,开胃健身",
        "益肾气,养胆明目,治虚劳寒冷,五劳七伤",
        "满满一口羊小排，让、您身、心皆怡",
      ],
      des_hant: [
        "細選優質羊排骨中肋骨瘦小的部分羊小排，肉層厚實，有軟骨",
        "肥瘦結合，質地鬆軟，肉質鮮美柔嫩",
        "古醫有云“羊肉能暖中補虛,補中益氣,開胃健身",
        "益腎氣,養膽明目,治虛勞寒冷,五勞七傷",
        "滿滿一口羊小排，讓、您身、心皆怡",
      ],
      endes: ` Select the thin ribs of a good lamb chop, with thick layers of meat and cartilage. 
      Combination of fat and lean, soft texture, delicious and tender meat ,  
      The ancient doctor said," mutton can warm and replenish deficiency, eplenish qi, appetizer and fitness,  
      Tonifying kidney Qi, nourishing gallbladder and brightening eyes, treating deficiency and cold, and suffering from five or seven wounds ,  
      A mouthful of lamb chops will make your body and heart happy. `,
    },
    {
      source: "/vertical/鸡肉/雞軟骨.jpg",
      name: "鸡软骨 ",
      name_hant: "雞軟骨",
      enname: "FRENCHED LAMB CHOP",
      des: [
        "精选每只鸡的鸡胸软骨和鸡腿",
        "配以独家研制酱料",
        "配以炭火烤烧，口感绝美",
        "每块软骨和无骨鸡腿肉搭配一口清酒",
        "美酒佳肴具兼得",
      ],
      des_hant: [
        "細選優質羊排骨中肋骨瘦小的部分羊小排，肉層厚實，有軟骨",
        "肥瘦結合，質地鬆軟，肉質鮮美柔嫩",
        "古醫有云“羊肉能暖中補虛,補中益氣,開胃健身",
        "益腎氣,養膽明目,治虛勞寒冷,五勞七傷",
        "滿滿一口羊小排，讓、您身、心皆怡",
      ],
      endes: ` Select the thin ribs of a good lamb chop, with thick layers of meat and cartilage. 
      Combination of fat and lean, soft texture, delicious and tender meat ,  
      The ancient doctor said," mutton can warm and replenish deficiency, eplenish qi, appetizer and fitness,  
      Tonifying kidney Qi, nourishing gallbladder and brightening eyes, treating deficiency and cold, and suffering from five or seven wounds ,  
      A mouthful of lamb chops will make your body and heart happy. `,
    },
    {
      source: "/vertical/鸡肉/去骨土雞腿肉.jpg",
      name: "去骨土鸡腿肉 ",
      name_hant: "去骨土雞腿肉",
      enname: "FRENCHED LAMB CHOP",
      des: [
        "细选优质羊排骨中肋骨瘦小的部分羊小排，肉层厚实，有软骨",
        "肥瘦结合，质地松软，肉质鲜美柔嫩",
        "古医有云“羊肉能暖中补虚,补中益气,开胃健身",
        "益肾气,养胆明目,治虚劳寒冷,五劳七伤",
        "满满一口羊小排，让、您身、心皆怡",
      ],
      des_hant: [
        "細選優質羊排骨中肋骨瘦小的部分羊小排，肉層厚實，有軟骨",
        "肥瘦結合，質地鬆軟，肉質鮮美柔嫩",
        "古醫有云“羊肉能暖中補虛,補中益氣,開胃健身",
        "益腎氣,養膽明目,治虛勞寒冷,五勞七傷",
        "滿滿一口羊小排，讓、您身、心皆怡",
      ],
      endes: ` Select the thin ribs of a good lamb chop, with thick layers of meat and cartilage. 
      Combination of fat and lean, soft texture, delicious and tender meat ,  
      The ancient doctor said," mutton can warm and replenish deficiency, eplenish qi, appetizer and fitness,  
      Tonifying kidney Qi, nourishing gallbladder and brightening eyes, treating deficiency and cold, and suffering from five or seven wounds ,  
      A mouthful of lamb chops will make your body and heart happy. `,
    },
    {
      source: "/vertical/鸡肉/焱烤手羽先.jpg",
      name: "焱烤手羽先",
      name_hant: "焱烤手羽先",
      enname: "FRIST A HAND IS ROASTED",
      des: ["鸡肉与蔬菜、水果的交融，", "口感脆嫩微甜，健康又美味", "", ""],
      des_hant: [
        "雞肉與蔬菜、水果的交融，",
        "口感脆嫩微甜，健康又美味",
        "",
        "",
      ],
      endes: `   The combination of chicken with vegetables and fruits 
      makes it crisp and sweet, healthy and delicious. `,
    },
  ],
  [
    {
      source: "/vertical/海鲜/草蝦.jpg",
      name: "草虾 ",
      name_hant: "草蝦",
      enname: "NERITIC SQUID",
      des: [
        "挑选优质海域海鲜，",
        "从海里到碗里，全程冷链，",
        "极致的保鲜，就像厨房在海边",
        "海中珍馐，59与您共享",
      ],
      des_hant: [
        "挑選優質海域海鮮，",
        "從海里到碗裏，全程冷鏈，",
        "極致的保鮮，就像廚房在海邊",
        "海中珍饈，59與您共享",
      ],
      endes: `  Choose quality Marine seafood,  
      From the sea to the bowl, the whole cold chain, 
      Extreme freshness, like the kitchen on the beach,
      Delicacies of the sea, 59 to share with you , `,
    },
    {
      source: "/vertical/海鲜/花枝.jpg",
      name: "花枝",
      name_hant: "花枝",
      enname: "CUTTLEFISH",
      des: [
        "挑选优质海域海鲜，",
        "从海里到碗里，全程冷链，",
        "极致的保鲜，就像厨房在海边",
        "海中珍馐，59与您共享",
      ],
      des_hant: [
        "挑選優質海域海鮮，",
        "從海里到碗裏，全程冷鏈，",
        "極致的保鮮，就像廚房在海邊",
        "海中珍饈，59與您共享",
      ],
      endes: `  Choose quality Marine seafood,  
      From the sea to the bowl, the whole cold chain, 
      Extreme freshness, like the kitchen on the beach,
      Delicacies of the sea, 59 to share with you , `,
    },
    {
      source: "/vertical/海鲜/墨魚香腸.jpg",
      name: "墨鱼香肠",
      name_hant: "墨魚香腸",
      enname: "CUTTLEFISH SAUSAGE",
      des: [
        "挑选优质海域海鲜，",
        "从海里到碗里，全程冷链，",
        "极致的保鲜，就像厨房在海边",
        "海中珍馐，59与您共享",
      ],
      des_hant: [
        "挑選優質海域海鮮，",
        "從海里到碗裏，全程冷鏈，",
        "極致的保鮮，就像廚房在海邊",
        "海中珍饈，59與您共享",
      ],
      endes: `  Choose quality Marine seafood,  
      From the sea to the bowl, the whole cold chain, 
      Extreme freshness, like the kitchen on the beach,
      Delicacies of the sea, 59 to share with you , `,
    },
    {
      source: "/vertical/海鲜/軟絲.jpg",
      name: "软丝 ",
      name_hant: "軟絲",
      enname: "NERITIC SQUID",
      des: [
        "挑选优质海域海鲜，",
        "从海里到碗里，全程冷链，",
        "极致的保鲜，就像厨房在海边",
        "海中珍馐，59与您共享",
      ],
      des_hant: [
        "挑選優質海域海鮮，",
        "從海里到碗裏，全程冷鏈，",
        "極致的保鮮，就像廚房在海邊",
        "海中珍饈，59與您共享",
      ],
      endes: `  Choose quality Marine seafood,  
      From the sea to the bowl, the whole cold chain, 
      Extreme freshness, like the kitchen on the beach,
      Delicacies of the sea, 59 to share with you , `,
    },
    {
      source: "/vertical/海鲜/松葉蟹腳.jpg",
      name: "松叶蟹脚 ",
      name_hant: "松葉蟹腳",
      enname: "QUEEN SNOW CRAB LEG",
      des: [
        "挑选优质海域海鲜，",
        "从海里到碗里，全程冷链，",
        "极致的保鲜，就像厨房在海边",
        "海中珍馐，59与您共享",
      ],
      des_hant: [
        "挑選優質海域海鮮，",
        "從海里到碗裏，全程冷鏈，",
        "極致的保鮮，就像廚房在海邊",
        "海中珍饈，59與您共享",
      ],
      endes: `  Choose quality Marine seafood,  
      From the sea to the bowl, the whole cold chain, 
      Extreme freshness, like the kitchen on the beach,
      Delicacies of the sea, 59 to share with you , `,
    },
    {
      source: "/vertical/海鲜/蟹膏生干貝.jpg",
      name: "蟹膏生干贝",
      name_hant: "蟹膏生干貝",
      enname: "SCALLOP WITH RAW CRAB ROE SASHIMI",
      des: [
        "挑选优质海域海鲜，",
        "从海里到碗里，全程冷链，",
        "极致的保鲜，就像厨房在海边",
        "海中珍馐，59与您共享",
      ],
      des_hant: [
        "挑選優質海域海鮮，",
        "從海里到碗裏，全程冷鏈，",
        "極致的保鮮，就像廚房在海邊",
        "海中珍饈，59與您共享",
      ],
      endes: `  Choose quality Marine seafood,  
      From the sea to the bowl, the whole cold chain, 
      Extreme freshness, like the kitchen on the beach,
      Delicacies of the sea, 59 to share with you , `,
    },
    {
      source: "/vertical/海鲜/蟹味噌甲羅燒.jpg",
      name: "蟹味噌甲罗烧 ",
      name_hant: "蟹味噌甲羅燒",
      enname: "RAW CRAB ROE IN CRAB SHELL",
      des: [
        "挑选优质海域海鲜，",
        "从海里到碗里，全程冷链，",
        "极致的保鲜，就像厨房在海边",
        "海中珍馐，59与您共享",
      ],
      des_hant: [
        "挑選優質海域海鮮，",
        "從海里到碗裏，全程冷鏈，",
        "極致的保鮮，就像廚房在海邊",
        "海中珍饈，59與您共享",
      ],
      endes: `  Choose quality Marine seafood,  
      From the sea to the bowl, the whole cold chain, 
      Extreme freshness, like the kitchen on the beach,
      Delicacies of the sea, 59 to share with you , `,
    },
    {
      source: "/vertical/海鲜/鰩魚翅一夜干.jpg",
      name: "鳐鱼翅一夜干 ",
      name_hant: "鰩魚翅一夜干",
      enname: "SKATE FIN",
      des: [
        "挑选优质海域海鲜，",
        "从海里到碗里，全程冷链，",
        "极致的保鲜，就像厨房在海边",
        "海中珍馐，59与您共享",
      ],
      des_hant: [
        "挑選優質海域海鮮，",
        "從海里到碗裏，全程冷鏈，",
        "極致的保鮮，就像廚房在海邊",
        "海中珍饈，59與您共享",
      ],
      endes: `  Choose quality Marine seafood,  
      From the sea to the bowl, the whole cold chain, 
      Extreme freshness, like the kitchen on the beach,
      Delicacies of the sea, 59 to share with you , `,
    },
    {
      source: "/vertical/海鲜/鲑鱼.jpg",
      name: "鲑鱼 ",
      name_hant: "鲑鱼",
      enname: "SALMON",
      des: [
        "选以阿拉斯加海域鲑鱼，搭配小火烧制，",
        "片刻等待即可享受肉质细嫩，鲜香可口的 鲑鱼片",
        "",
        "",
      ],
      des_hant: [
        "選以阿拉斯加海域鮭魚，搭配小火燒制，",
        "片刻等待即可享受肉質細嫩，鮮香可口的 鮭魚片",
        "",
        "",
      ],
      endes: `  Choose THE Alaskan SEA salmon,
       with small fire, wait for a moment to enjoy the tender meat, delicious salmon fillet `,
    },
    {
      source: "/vertical/海鲜/鯖魚.jpg",
      name: "鯖魚 ",
      name_hant: "鯖魚",
      enname: "MACKEREL",
      des: [
        "鲭鱼含营养价值，在鱼界一骑绝尘，",
        "配以文火慢煎，再佐以独家酱料，",
        "香气扑鼻，老少皆宜",
        "",
      ],
      des_hant: [
        "鯖魚含營養價值，在魚界一騎絕塵，",
        "配以文火慢煎，再佐以獨家醬料，",
        "香氣撲鼻，老少皆宜",
        "",
      ],
      endes: `  Mackerel is one of the best fish in the world for its nutritional value. 
      Cooked over a low heat and served with an exclusive sauce, mackerel is delicious for all ages. `,
    },
    {
      source: "/vertical/海鲜/三味珍寶鮮干貝.jpg",
      name: "三味珍寶鮮干貝 ",
      name_hant: "三味珍寶鮮干貝",
      enname: "SANWEI TREASURE SCALLOPS",
      des: [
        "选以优质干贝，搭配珍贵食材，",
        "口感鲜嫩多汁，让味蕾享受“鲜”的魅力",
        "",
        "",
      ],
      des_hant: [
        "選以優質幹貝，搭配珍貴食材，",
        "口感鮮嫩多汁，讓味蕾享受“鮮”的魅力",
        "",
        "",
      ],
      endes: `  Selection of high quality scallops, with precious ingredients,
       fresh and juicy taste, let the taste buds enjoy the charm of "fresh".`,
    },
  ],
  [
    {
      source: "/vertical/甜点/自制地瓜起司.jpg",
      name: "自制地瓜起司",
      name_hant: "自制地瓜起司",
      enname: "HOMEMADE SWEET POTATO WITH CHEESE",
      des: [
        "美味多汁的烧肉配以甘甜细腻的甜品，",
        "两种浑然不同的风格和滋味感受，",
        "刷新您的触觉感官",
        "",
      ],
      des_hant: [
        "美味多汁的燒肉配以甘甜細膩的甜品，",
        "兩種渾然不同的風格和滋味感受，",
        "刷新您的觸覺感官",
        "",
      ],
      endes: `    Succulent roast meat with sweet and delicate desserts,.  
      Two totally different styles and tastes,  
      Refresh your sense of touch , `,
    },
    {
      source: "/vertical/甜点/自制焦糖布丁.jpg",
      name: "自制焦糖布丁",
      name_hant: "自制焦糖布丁",
      enname: "HOMEMADE CARAMEL PUDDING",
      des: [
        "美味多汁的烧肉配以甘甜细腻的甜品，",
        "两种浑然不同的风格和滋味感受，",
        "刷新您的触觉感官",
        "",
      ],
      des_hant: [
        "美味多汁的燒肉配以甘甜細膩的甜品，",
        "兩種渾然不同的風格和滋味感受，",
        "刷新您的觸覺感官",
        "",
      ],
      endes: `    Succulent roast meat with sweet and delicate desserts,.  
      Two totally different styles and tastes,  
      Refresh your sense of touch , `,
    },
  ],
  [
    {
      source: "/vertical/小菜/和風芥子洋蔥絲.jpg",
      name: "和风芥子洋葱丝 ",
      name_hant: "和風芥子洋蔥絲",
      enname: "JAPANESE DRESSING ONION",
      des: [
        "饱满清香的毛豆、",
        "酱香鲜艳的泡菜、",
        "清脆爽口的洋葱丝，",
        "都是您开胃伴饭的不二首选",
      ],
      des_hant: [
        "飽滿清香的毛豆、",
        "醬香鮮豔的泡菜、",
        "清脆爽口的洋蔥絲，",
        "都是您開胃伴飯的不二首選",
      ],
      endes: `   Select top quality rice, gently scrub and soak for 2 hours.  
      Let the grains of rice absorb all the water, full as beads,  
      Precise scientific method of rice and water proportion steaming and smothering,.  
      Every GRAIN OF RICE REVEALS the fragrance OF Chun CHUN rice, so you want to taste it first.  . `,
    },
    {
      source: "/vertical/小菜/毛豆.jpg",
      name: "毛豆",
      name_hant: "毛豆",
      enname: "EDAMAME",
      des: [
        "饱满清香的毛豆、",
        "酱香鲜艳的泡菜、",
        "清脆爽口的洋葱丝，",
        "都是您开胃伴饭的不二首选",
      ],
      des_hant: [
        "飽滿清香的毛豆、",
        "醬香鮮豔的泡菜、",
        "清脆爽口的洋蔥絲，",
        "都是您開胃伴飯的不二首選",
      ],
      endes: `   Select top quality rice, gently scrub and soak for 2 hours.  
      Let the grains of rice absorb all the water, full as beads,  
      Precise scientific method of rice and water proportion steaming and smothering,.  
      Every GRAIN OF RICE REVEALS the fragrance OF Chun CHUN rice, so you want to taste it first.  . `,
    },
    {
      source: "/vertical/小菜/泡菜.jpg",
      name: "泡菜",
      name_hant: "泡菜",
      enname: "KIMCHI",
      des: [
        "饱满清香的毛豆、",
        "酱香鲜艳的泡菜、",
        "清脆爽口的洋葱丝，",
        "都是您开胃伴饭的不二首选",
      ],
      des_hant: [
        "飽滿清香的毛豆、",
        "醬香鮮豔的泡菜、",
        "清脆爽口的洋蔥絲，",
        "都是您開胃伴飯的不二首選",
      ],
      endes: `   Select top quality rice, gently scrub and soak for 2 hours.  
      Let the grains of rice absorb all the water, full as beads,  
      Precise scientific method of rice and water proportion steaming and smothering,.  
      Every GRAIN OF RICE REVEALS the fragrance OF Chun CHUN rice, so you want to taste it first.  . `,
    },
    {
      source: "/vertical/小菜/胡董招牌清燉牛肉湯.jpg",
      name: "胡董招牌清燉牛肉湯",
      name_hant: "胡董招牌清燉牛肉湯",
      enname: "CONSOMME BEEF SOUP",
      des: [
        "清爽的牛肉湯，有別於紅燒的重口味，",
        "這是屬於台灣南部的特色美食，清甜湯頭，",
        "不油不膩，滋补俱佳，风味绝佳",
        "",
      ],
      des_hant: [
        "清爽的牛肉湯，有別於紅燒的重口味，",
        "這是屬於臺灣南部的特色美食，清甜湯頭，",
        "不油不膩，滋補俱佳，風味絕佳",
        "",
      ],
      endes: `   Fresh BEEF SOUP, DIFFERENT FROM THE heavy taste of BROWN sauce, THIS is a SPECIAL foo
      d in southern Taiwan, sweet soup, not oily, not greasy, nourishing, excellent flavor. `,
    },
  ],
  [
    {
      source: "/vertical/主食/白飯.jpg",
      name: "白饭",
      name_hant: "白飯",
      enname: "JAPANESE RICE",
      des: [
        "选用优质特等大米，轻柔搓洗，浸泡2小时，",
        "让米粒充分吸收水分，颗颗饱满如珠",
        "精准的科学米水比例蒸煮、闷蒸方法，",
        "每一粒米粒都透露出淳淳的米香，让您欲先一品。",
      ],
      des_hant: [
        "選用優質特等大米，輕柔搓洗，浸泡2小時，",
        "讓米粒充分吸收水分，顆顆飽滿如珠",
        "精準的科學米水比例蒸煮、悶蒸方法，",
        "每一粒米粒都透露出淳淳的米香，讓您欲先一品。",
      ],
      endes: `   With fresh and tender cabbage, kale and kelp,
      With some sesame seeds, and then a drizzle of fresh, sweet and sour lime juice,  
      It's a simple mix, every bite is crisp, 
      A touch of sweet and sour filling the mouth is the most wonderful appetize `,
    },
    {
      source: "/vertical/主食/鮭魚茶泡飯.jpg",
      name: "鲑鱼茶泡饭 ",
      name_hant: "鮭魚茶泡飯",
      enname: "OCHAZUKE JAPANESE RICE SOUP",
      des: [
        "选用优质特等大米，轻柔搓洗，浸泡2小时，",
        "让米粒充分吸收水分，颗颗饱满如珠",
        "精准的科学米水比例蒸煮、闷蒸方法，",
        "每一粒米粒都透露出淳淳的米香，让您欲先一品。",
      ],
      des_hant: [
        "選用優質特等大米，輕柔搓洗，浸泡2小時，",
        "讓米粒充分吸收水分，顆顆飽滿如珠",
        "精準的科學米水比例蒸煮、悶蒸方法，",
        "每一粒米粒都透露出淳淳的米香，讓您欲先一品。",
      ],
      endes: `   With fresh and tender cabbage, kale and kelp,
      With some sesame seeds, and then a drizzle of fresh, sweet and sour lime juice,  
      It's a simple mix, every bite is crisp, 
      A touch of sweet and sour filling the mouth is the most wonderful appetize `,
    },
  ],
  [
    {
      source: "/vertical/沙拉/綜合沙拉.jpg",
      name: "综合沙拉",
      name_hant: "綜合沙拉",
      enname: "HOUSE SPECIAL SALAD",
      des: [
        "配以新鲜青嫩的包菜、甘蓝和海带，",
        "着上些许芝麻，最后淋上清爽酸甜的青柠汁水，",
        "简单的搅拌均匀，每口都清脆爽口，",
        "淡淡的酸甜充斥着口腔，是最为美妙的开胃前菜。",
      ],
      des_hant: [
        "配以新鮮青嫩的包菜、甘藍和海帶，",
        "着上些許芝麻，最後淋上清爽酸甜的青檸汁水，",
        "簡單的攪拌均勻，每口都清脆爽口，",
        "淡淡的酸甜充斥着口腔，是最爲美妙的開胃前菜。",
      ],
      endes: `   Meat, fish and meat, but also gain and loss,
      Plain, no ZI tasteless, but also have joy and joy. .  
      We choose fresh and tender vegetables, 
      Let this fresh green stuff flow through,
      Into thy eyes, 
      Into your belly.`,
    },
    {
      source: "/vertical/沙拉/鸡胸沙拉.jpg",
      name: "鸡胸沙拉",
      name_hant: "鸡胸沙拉",
      enname: "CHICKEN SALAD",
      des: ["鸡肉与蔬菜、水果的交融，", "口感脆嫩微甜，健康又美味", "", ""],
      des_hant: [
        "雞肉與蔬菜、水果的交融，",
        "口感脆嫩微甜，健康又美味",
        "",
        "",
      ],
      endes: `  The combination of chicken with vegetables and fruits makes
       it crisp and sweet, healthy and delicious.`,
    },
    {
      source: "/vertical/素菜/青椒.jpg",
      name: "青椒",
      name_hant: "青椒",
      enname: "HOUSE SPECIAL SALAD",
      des: [
        "配以新鲜青嫩的包菜、甘蓝和海带，",
        "着上些许芝麻，最后淋上清爽酸甜的青柠汁水，",
        "简单的搅拌均匀，每口都清脆爽口，",
        "淡淡的酸甜充斥着口腔，是最为美妙的开胃前菜。",
      ],
      des_hant: [
        "配以新鮮青嫩的包菜、甘藍和海帶，",
        "着上些許芝麻，最後淋上清爽酸甜的青檸汁水，",
        "簡單的攪拌均勻，每口都清脆爽口，",
        "淡淡的酸甜充斥着口腔，是最爲美妙的開胃前菜。",
      ],
      endes: `   Meat, fish and meat, but also gain and loss,
      Plain, no ZI tasteless, but also have joy and joy. .  
      We choose fresh and tender vegetables, 
      Let this fresh green stuff flow through,
      Into thy eyes, 
      Into your belly.`,
    },
    {
      source: "/vertical/素菜/日本山藥.jpg",
      name: "日本山药 ",
      name_hant: "日本山藥",
      enname: "JAPANESE YAM",
      des: [
        "配以新鲜青嫩的包菜、甘蓝和海带，",
        "着上些许芝麻，最后淋上清爽酸甜的青柠汁水，",
        "简单的搅拌均匀，每口都清脆爽口，",
        "淡淡的酸甜充斥着口腔，是最为美妙的开胃前菜。",
      ],
      des_hant: [
        "配以新鮮青嫩的包菜、甘藍和海帶，",
        "着上些許芝麻，最後淋上清爽酸甜的青檸汁水，",
        "簡單的攪拌均勻，每口都清脆爽口，",
        "淡淡的酸甜充斥着口腔，是最爲美妙的開胃前菜。",
      ],
      endes: `   Meat, fish and meat, but also gain and loss,
      Plain, no ZI tasteless, but also have joy and joy. .  
      We choose fresh and tender vegetables, 
      Let this fresh green stuff flow through,
      Into thy eyes, 
      Into your belly.`,
    },
  ],

  [
    {
      source: "/vertical/素菜/青椒.jpg",
      name: "青椒",
      name_hant: "青椒",
      enname: "JAPANESE YAM",
      des: [
        "荤，有鱼有肉，却也有得有失，",
        "素，无滋无味，却也有欢有乐。",
        "我们选以新鲜青嫩的蔬菜，",
        "让这份清新的绿色食材间中流动，",
        "流进您的眼睛，",
        "融入您的腹中。",
      ],
      des_hant: [
        "葷，有魚有肉，卻也有得有失，",
        "素，無滋無味，卻也有歡有樂。",
        "我們選以新鮮青嫩的蔬菜，",
        "讓這份清新的綠色食材間中流動，",
        "流進您的眼睛，",
        "融入您的腹中。",
      ],
      endes: `   Fine dishes and fine wine,
      Everything else has, ,  
      For those of you who don't drink, we have a number of exclusive specialty drinks,  
    Never give up eating and drinking , `,
    },
    {
      source: "/vertical/素菜/日本山藥.jpg",
      name: "日本山药",
      name_hant: "日本山藥",
      enname: "CORN",
      des: [
        "荤，有鱼有肉，却也有得有失，",
        "素，无滋无味，却也有欢有乐。",
        "我们选以新鲜青嫩的蔬菜，",
        "让这份清新的绿色食材间中流动，",
        "流进您的眼睛，",
        "融入您的腹中。",
      ],
      des_hant: [
        "葷，有魚有肉，卻也有得有失，",
        "素，無滋無味，卻也有歡有樂。",
        "我們選以新鮮青嫩的蔬菜，",
        "讓這份清新的綠色食材間中流動，",
        "流進您的眼睛，",
        "融入您的腹中。",
      ],
      endes: `   Fine dishes and fine wine,
      Everything else has, ,  
      For those of you who don't drink, we have a number of exclusive specialty drinks,  
    Never give up eating and drinking , `,
    },
    {
      source: "/vertical/素菜/生菜.jpg",
      name: "生菜",
      name_hant: "生菜",
      enname: "ZUCCHINI",
      des: [
        "荤，有鱼有肉，却也有得有失，",
        "素，无滋无味，却也有欢有乐。",
        "我们选以新鲜青嫩的蔬菜，",
        "让这份清新的绿色食材间中流动，",
        "流进您的眼睛，",
        "融入您的腹中。",
      ],
      des_hant: [
        "葷，有魚有肉，卻也有得有失，",
        "素，無滋無味，卻也有歡有樂。",
        "我們選以新鮮青嫩的蔬菜，",
        "讓這份清新的綠色食材間中流動，",
        "流進您的眼睛，",
        "融入您的腹中。",
      ],
      endes: `   Fine dishes and fine wine,
      Everything else has, ,  
      For those of you who don't drink, we have a number of exclusive specialty drinks,  
    Never give up eating and drinking , `,
    },
    {
      source: "/vertical/素菜/杏鮑菇.jpg",
      name: "杏鲍菇 ",
      name_hant: "杏鮑菇",
      enname: "KING OYSTER MUSHROOM",
      des: [
        "荤，有鱼有肉，却也有得有失，",
        "素，无滋无味，却也有欢有乐。",
        "我们选以新鲜青嫩的蔬菜，",
        "让这份清新的绿色食材间中流动，",
        "流进您的眼睛，",
        "融入您的腹中。",
      ],
      des_hant: [
        "葷，有魚有肉，卻也有得有失，",
        "素，無滋無味，卻也有歡有樂。",
        "我們選以新鮮青嫩的蔬菜，",
        "讓這份清新的綠色食材間中流動，",
        "流進您的眼睛，",
        "融入您的腹中。",
      ],
      endes: `   Fine dishes and fine wine,
      Everything else has, ,  
      For those of you who don't drink, we have a number of exclusive specialty drinks,  
    Never give up eating and drinking , `,
    },
    {
      source: "/vertical/素菜/玉米.jpg",
      name: "玉米",
      name_hant: "玉米",
      enname: "CAPSICUM",
      des: [
        "荤，有鱼有肉，却也有得有失，",
        "素，无滋无味，却也有欢有乐。",
        "我们选以新鲜青嫩的蔬菜，",
        "让这份清新的绿色食材间中流动，",
        "流进您的眼睛，",
        "融入您的腹中。",
      ],
      des_hant: [
        "葷，有魚有肉，卻也有得有失，",
        "素，無滋無味，卻也有歡有樂。",
        "我們選以新鮮青嫩的蔬菜，",
        "讓這份清新的綠色食材間中流動，",
        "流進您的眼睛，",
        "融入您的腹中。",
      ],
      endes: `   Fine dishes and fine wine,
      Everything else has, ,  
      For those of you who don't drink, we have a number of exclusive specialty drinks,  
    Never give up eating and drinking , `,
    },
    {
      source: "/vertical/素菜/櫛瓜.jpg",
      name: "栉瓜 ",
      name_hant: "櫛瓜",
      enname: "LETTUCE",
      des: [
        "荤，有鱼有肉，却也有得有失，",
        "素，无滋无味，却也有欢有乐。",
        "我们选以新鲜青嫩的蔬菜，",
        "让这份清新的绿色食材间中流动，",
        "流进您的眼睛，",
        "融入您的腹中。",
      ],
      des_hant: [
        "葷，有魚有肉，卻也有得有失，",
        "素，無滋無味，卻也有歡有樂。",
        "我們選以新鮮青嫩的蔬菜，",
        "讓這份清新的綠色食材間中流動，",
        "流進您的眼睛，",
        "融入您的腹中。",
      ],
      endes: `   Fine dishes and fine wine,
      Everything else has, ,  
      For those of you who don't drink, we have a number of exclusive specialty drinks,  
    Never give up eating and drinking , `,
    },
  ],
  [
    {
      source: "/vertical/饮料/薑汁汽水.jpg",
      name: "姜汁汽水 ",
      name_hant: "薑汁汽水",
      enname: "GINGLE ALE",
      des: [
        "美肴与美酒，",
        "其他皆具有，",
        "我们为不喝酒的您提供了多款独家特色饮料，",
        "吃与喝“不离不弃”",
      ],
      des_hant: [
        "美餚與美酒，",
        "其他皆具有，",
        "我們爲不喝酒的您提供了多款獨家特色飲料，",
        "吃與喝“不離不棄”",
      ],
      endes: `   Foodandwine,everythingelse,weprovideavarietyofexclusivespecialdrinksfor
      youwhodonotdrink,eatanddrink"neverleave"`,
    },
    {
      source: "/vertical/饮料/可爾必思.jpg",
      name: "可尔必思 ",
      name_hant: "可爾必思",
      enname: "CALPIS SODA / WATER",
      des: [
        "美肴与美酒，",
        "其他皆具有，",
        "我们为不喝酒的您提供了多款独家特色饮料，",
        "吃与喝“不离不弃”",
      ],
      des_hant: [
        "美餚與美酒，",
        "其他皆具有，",
        "我們爲不喝酒的您提供了多款獨家特色飲料，",
        "吃與喝“不離不棄”",
      ],
      endes: `   Foodandwine,everythingelse,weprovideavarietyofexclusivespecialdrinksfor
      youwhodonotdrink,eatanddrink"neverleave"`,
    },
    {
      source: "/vertical/饮料/可樂.jpg",
      name: "可乐",
      name_hant: "可樂",
      enname: "COCA-COLA",
      des: [
        "美肴与美酒，",
        "其他皆具有，",
        "我们为不喝酒的您提供了多款独家特色饮料，",
        "吃与喝“不离不弃”",
      ],
      des_hant: [
        "美餚與美酒，",
        "其他皆具有，",
        "我們爲不喝酒的您提供了多款獨家特色飲料，",
        "吃與喝“不離不棄”",
      ],
      endes: `   Foodandwine,everythingelse,weprovideavarietyofexclusivespecialdrinksfor
      youwhodonotdrink,eatanddrink"neverleave"`,
    },
    {
      source: "/vertical/饮料/柳橙汁.jpg",
      name: "柳橙汁",
      name_hant: "柳橙汁",
      enname: "ORANGE JUICE",
      des: [
        "美肴与美酒，",
        "其他皆具有，",
        "我们为不喝酒的您提供了多款独家特色饮料，",
        "吃与喝“不离不弃”",
      ],
      des_hant: [
        "美餚與美酒，",
        "其他皆具有，",
        "我們爲不喝酒的您提供了多款獨家特色飲料，",
        "吃與喝“不離不棄”",
      ],
      endes: `   Foodandwine,everythingelse,weprovideavarietyofexclusivespecialdrinksfor
      youwhodonotdrink,eatanddrink"neverleave"`,
    },
    {
      source: "/vertical/饮料/天然氣泡礦泉水.jpg",
      name: "天然气泡矿泉水 ",
      name_hant: "天然氣泡礦泉水",
      enname: "SAN PELLEGRINO SPARKLING",
      des: [
        "美肴与美酒，",
        "其他皆具有，",
        "我们为不喝酒的您提供了多款独家特色饮料，",
        "吃与喝“不离不弃”",
      ],
      des_hant: [
        "美餚與美酒，",
        "其他皆具有，",
        "我們爲不喝酒的您提供了多款獨家特色飲料，",
        "吃與喝“不離不棄”",
      ],
      endes: `   Foodandwine,everythingelse,weprovideavarietyofexclusivespecialdrinksfor
      youwhodonotdrink,eatanddrink"neverleave"`,
    },
    {
      source: "/vertical/饮料/文山包種.jpg",
      name: "文山包种 ",
      name_hant: "文山包種",
      enname: "JOOLONG TEA - HOT/COLD(REFILLABLE)",
      des: [
        "美肴与美酒，",
        "其他皆具有，",
        "我们为不喝酒的您提供了多款独家特色饮料，",
        "吃与喝“不离不弃”",
      ],
      des_hant: [
        "美餚與美酒，",
        "其他皆具有，",
        "我們爲不喝酒的您提供了多款獨家特色飲料，",
        "吃與喝“不離不棄”",
      ],
      endes: `   Foodandwine,everythingelse,weprovideavarietyofexclusivespecialdrinksfor
      youwhodonotdrink,eatanddrink"neverleave"`,
    },
    {
      source: "/vertical/饮料/雪碧.jpg",
      name: "雪碧",
      name_hant: "雪碧",
      enname: "XUE BI",
      des: [
        "美肴与美酒，",
        "其他皆具有，",
        "我们为不喝酒的您提供了多款独家特色饮料，",
        "吃与喝“不离不弃”",
      ],
      des_hant: [
        "美餚與美酒，",
        "其他皆具有，",
        "我們爲不喝酒的您提供了多款獨家特色飲料，",
        "吃與喝“不離不棄”",
      ],
      endes: `   Foodandwine,everythingelse,weprovideavarietyofexclusivespecialdrinksfor
      youwhodonotdrink,eatanddrink"neverleave"`,
    },
  ],
];
const menus = [
  { id: 1, name: "日本和牛" },
  { id: 2, name: "澳洲和牛" },
  { id: 3, name: "美國牛肉" },
  { id: 4, name: "豬肉" },
  { id: 5, name: "雞肉" },
  { id: 6, name: "羊肉" },
  { id: 7, name: "海鮮" },
  { id: 8, name: "甜點" },
  { id: 9, name: "小菜" },
  { id: 10, name: "主食" },
  { id: 11, name: "沙拉" },
  { id: 12, name: "蔬菜" },
  { id: 13, name: "飲料" },
];
const menus_hant = [
  { id: 1, name: "日本和牛" },
  { id: 2, name: "澳洲和牛" },
  { id: 3, name: "美国牛肉" },
  { id: 4, name: "猪肉" },
  { id: 5, name: "鸡肉" },
  { id: 6, name: "羊肉" },
  { id: 7, name: "海鲜" },
  { id: 8, name: "甜点" },
  { id: 9, name: "小菜" },
  { id: 10, name: "主食" },
  { id: 11, name: "沙拉" },
  { id: 12, name: "蔬菜" },
  { id: 13, name: "饮料" },
];
const EnMenus = [
  { id: 1, name: "AUSTRALIAN WAGYU" },
  { id: 2, name: "AMERICAN BEEF" },
  { id: 3, name: "JAPANESE WAGYU A5" },
  { id: 4, name: "PORK" },
  { id: 5, name: "CHICKEN" },
  { id: 6, name: "MUTTON" },
  { id: 7, name: "SEAFOOD" },
  { id: 8, name: "DESSERT" },
  { id: 9, name: "SIDES" },
  { id: 10, name: "MAIN MEALS" },
  { id: 11, name: "SALAD" },
  { id: 12, name: "VEGETABLES" },
  { id: 13, name: "BEVERAGES" },
];
export { DishesList, menus, EnMenus, menus_hant };
